# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ai_service.proto',
  package='',
  serialized_pb='\n\x10\x61i_service.proto2\x0b\n\tAIServiceB\x03\x90\x01\x01')





_AISERVICE = descriptor.ServiceDescriptor(
  name='AIService',
  full_name='AIService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=20,
  serialized_end=31,
  methods=[
])

class AIService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _AISERVICE
class AIService_Stub(AIService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _AISERVICE

# @@protoc_insertion_point(module_scope)
