# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import entity_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='entity_service.proto',
  package='',
  serialized_pb='\n\x14\x65ntity_service.proto\x1a\x0c\x65ntity.proto\"\x18\n\x16GetPlayerIDListRequest\"\x15\n\x06IDList\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\x06\n\x04Void2\xd9\x02\n\rEntityService\x12 \n\x0c\x43reatePlayer\x12\x07.Player\x1a\x07.Player\x12\x1a\n\nCreateItem\x12\x05.Item\x1a\x05.Item\x12\x1d\n\x0b\x43reateChest\x12\x06.Chest\x1a\x06.Chest\x12)\n\x0f\x43reateCharacter\x12\n.Character\x1a\n.Character\x12\x17\n\tCreateMob\x12\x04.Mob\x1a\x04.Mob\x12\x1d\n\tGetPlayer\x12\x07.Player\x1a\x07.Player\x12\x14\n\x06GetMob\x12\x04.Mob\x1a\x04.Mob\x12\x33\n\x0fGetPlayerIDList\x12\x17.GetPlayerIDListRequest\x1a\x07.IDList\x12\x1e\n\x0cUpdateEntity\x12\x07.Entity\x1a\x05.Void\x12\x1d\n\tGetEntity\x12\x07.Entity\x1a\x07.EntityB\x03\x90\x01\x01')




_GETPLAYERIDLISTREQUEST = descriptor.Descriptor(
  name='GetPlayerIDListRequest',
  full_name='GetPlayerIDListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=62,
)


_IDLIST = descriptor.Descriptor(
  name='IDList',
  full_name='IDList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ids', full_name='IDList.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=64,
  serialized_end=85,
)


_VOID = descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['GetPlayerIDListRequest'] = _GETPLAYERIDLISTREQUEST
DESCRIPTOR.message_types_by_name['IDList'] = _IDLIST
DESCRIPTOR.message_types_by_name['Void'] = _VOID

class GetPlayerIDListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETPLAYERIDLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:GetPlayerIDListRequest)

class IDList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDLIST
  
  # @@protoc_insertion_point(class_scope:IDList)

class Void(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOID
  
  # @@protoc_insertion_point(class_scope:Void)


_ENTITYSERVICE = descriptor.ServiceDescriptor(
  name='EntityService',
  full_name='EntityService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=96,
  serialized_end=441,
  methods=[
  descriptor.MethodDescriptor(
    name='CreatePlayer',
    full_name='EntityService.CreatePlayer',
    index=0,
    containing_service=None,
    input_type=entity_pb2._PLAYER,
    output_type=entity_pb2._PLAYER,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='CreateItem',
    full_name='EntityService.CreateItem',
    index=1,
    containing_service=None,
    input_type=entity_pb2._ITEM,
    output_type=entity_pb2._ITEM,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='CreateChest',
    full_name='EntityService.CreateChest',
    index=2,
    containing_service=None,
    input_type=entity_pb2._CHEST,
    output_type=entity_pb2._CHEST,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='CreateCharacter',
    full_name='EntityService.CreateCharacter',
    index=3,
    containing_service=None,
    input_type=entity_pb2._CHARACTER,
    output_type=entity_pb2._CHARACTER,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='CreateMob',
    full_name='EntityService.CreateMob',
    index=4,
    containing_service=None,
    input_type=entity_pb2._MOB,
    output_type=entity_pb2._MOB,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='GetPlayer',
    full_name='EntityService.GetPlayer',
    index=5,
    containing_service=None,
    input_type=entity_pb2._PLAYER,
    output_type=entity_pb2._PLAYER,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='GetMob',
    full_name='EntityService.GetMob',
    index=6,
    containing_service=None,
    input_type=entity_pb2._MOB,
    output_type=entity_pb2._MOB,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='GetPlayerIDList',
    full_name='EntityService.GetPlayerIDList',
    index=7,
    containing_service=None,
    input_type=_GETPLAYERIDLISTREQUEST,
    output_type=_IDLIST,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='UpdateEntity',
    full_name='EntityService.UpdateEntity',
    index=8,
    containing_service=None,
    input_type=entity_pb2._ENTITY,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='GetEntity',
    full_name='EntityService.GetEntity',
    index=9,
    containing_service=None,
    input_type=entity_pb2._ENTITY,
    output_type=entity_pb2._ENTITY,
    options=None,
  ),
])

class EntityService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ENTITYSERVICE
class EntityService_Stub(EntityService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ENTITYSERVICE

# @@protoc_insertion_point(module_scope)
