# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='event_service.proto',
  package='',
  serialized_pb='\n\x13\x65vent_service.proto\"\x06\n\x04Void\"\'\n\x12PlayerLoginedEvent\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\";\n\x14\x45ntityJoinWorldEvent\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\x10\n\x08world_id\x18\x02 \x01(\x05\"U\n\x15PopulationUpdateEvent\x12\x10\n\x08world_id\x18\x01 \x01(\x05\x12\x16\n\x0epre_population\x18\x02 \x01(\x05\x12\x12\n\npopulation\x18\x03 \x01(\x05\"T\n\x17\x45ntityGroupChangedEvent\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x14\n\x0cpre_group_id\x18\x03 \x01(\t\"X\n\x0f\x45ntityMoveEvent\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05pre_x\x18\x04 \x01(\x05\x12\r\n\x05pre_y\x18\x05 \x01(\x05\"3\n\x0b\x41ttackEvent\x12\x11\n\tattack_id\x18\x01 \x01(\x05\x12\x11\n\ttarget_id\x18\x02 \x01(\x05\"\xa8\x01\n\x0b\x44\x61mageEvent\x12\x11\n\tattack_id\x18\x01 \x01(\x05\x12\x11\n\ttarget_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x64\x61mage\x18\x03 \x01(\x05\x12\x15\n\rattack_weapon\x18\x04 \x01(\x05\x12\x14\n\x0ctarget_armor\x18\x05 \x01(\x05\x12\x1c\n\x14pre_target_hitpoints\x18\x06 \x01(\x05\x12\x18\n\x10target_hitpoints\x18\x07 \x01(\x05\"1\n\tKillEvent\x12\x11\n\tkiller_id\x18\x01 \x01(\x05\x12\x11\n\tkilled_id\x18\x02 \x01(\x05\x32\xd6\x02\n\x0c\x45ventService\x12+\n\rPlayerLogined\x12\x13.PlayerLoginedEvent\x1a\x05.Void\x12/\n\x0f\x45ntityJoinWorld\x12\x15.EntityJoinWorldEvent\x1a\x05.Void\x12\x31\n\x10PopulationUpdate\x12\x16.PopulationUpdateEvent\x1a\x05.Void\x12\x35\n\x12\x45ntityGroupChanged\x12\x18.EntityGroupChangedEvent\x1a\x05.Void\x12%\n\nEntityMove\x12\x10.EntityMoveEvent\x1a\x05.Void\x12\x1d\n\x06\x41ttack\x12\x0c.AttackEvent\x1a\x05.Void\x12\x1d\n\x06\x44\x61mage\x12\x0c.DamageEvent\x1a\x05.Void\x12\x19\n\x04Kill\x12\n.KillEvent\x1a\x05.VoidB\x03\x90\x01\x01')




_VOID = descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=29,
)


_PLAYERLOGINEDEVENT = descriptor.Descriptor(
  name='PlayerLoginedEvent',
  full_name='PlayerLoginedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player_id', full_name='PlayerLoginedEvent.player_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=70,
)


_ENTITYJOINWORLDEVENT = descriptor.Descriptor(
  name='EntityJoinWorldEvent',
  full_name='EntityJoinWorldEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='EntityJoinWorldEvent.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='world_id', full_name='EntityJoinWorldEvent.world_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=131,
)


_POPULATIONUPDATEEVENT = descriptor.Descriptor(
  name='PopulationUpdateEvent',
  full_name='PopulationUpdateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='world_id', full_name='PopulationUpdateEvent.world_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pre_population', full_name='PopulationUpdateEvent.pre_population', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='population', full_name='PopulationUpdateEvent.population', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=218,
)


_ENTITYGROUPCHANGEDEVENT = descriptor.Descriptor(
  name='EntityGroupChangedEvent',
  full_name='EntityGroupChangedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='EntityGroupChangedEvent.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group_id', full_name='EntityGroupChangedEvent.group_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pre_group_id', full_name='EntityGroupChangedEvent.pre_group_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=304,
)


_ENTITYMOVEEVENT = descriptor.Descriptor(
  name='EntityMoveEvent',
  full_name='EntityMoveEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='EntityMoveEvent.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='x', full_name='EntityMoveEvent.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='EntityMoveEvent.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pre_x', full_name='EntityMoveEvent.pre_x', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pre_y', full_name='EntityMoveEvent.pre_y', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=306,
  serialized_end=394,
)


_ATTACKEVENT = descriptor.Descriptor(
  name='AttackEvent',
  full_name='AttackEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attack_id', full_name='AttackEvent.attack_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_id', full_name='AttackEvent.target_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=396,
  serialized_end=447,
)


_DAMAGEEVENT = descriptor.Descriptor(
  name='DamageEvent',
  full_name='DamageEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='attack_id', full_name='DamageEvent.attack_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_id', full_name='DamageEvent.target_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='damage', full_name='DamageEvent.damage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attack_weapon', full_name='DamageEvent.attack_weapon', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_armor', full_name='DamageEvent.target_armor', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pre_target_hitpoints', full_name='DamageEvent.pre_target_hitpoints', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_hitpoints', full_name='DamageEvent.target_hitpoints', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=450,
  serialized_end=618,
)


_KILLEVENT = descriptor.Descriptor(
  name='KillEvent',
  full_name='KillEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='killer_id', full_name='KillEvent.killer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='killed_id', full_name='KillEvent.killed_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=620,
  serialized_end=669,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['PlayerLoginedEvent'] = _PLAYERLOGINEDEVENT
DESCRIPTOR.message_types_by_name['EntityJoinWorldEvent'] = _ENTITYJOINWORLDEVENT
DESCRIPTOR.message_types_by_name['PopulationUpdateEvent'] = _POPULATIONUPDATEEVENT
DESCRIPTOR.message_types_by_name['EntityGroupChangedEvent'] = _ENTITYGROUPCHANGEDEVENT
DESCRIPTOR.message_types_by_name['EntityMoveEvent'] = _ENTITYMOVEEVENT
DESCRIPTOR.message_types_by_name['AttackEvent'] = _ATTACKEVENT
DESCRIPTOR.message_types_by_name['DamageEvent'] = _DAMAGEEVENT
DESCRIPTOR.message_types_by_name['KillEvent'] = _KILLEVENT

class Void(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOID
  
  # @@protoc_insertion_point(class_scope:Void)

class PlayerLoginedEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERLOGINEDEVENT
  
  # @@protoc_insertion_point(class_scope:PlayerLoginedEvent)

class EntityJoinWorldEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYJOINWORLDEVENT
  
  # @@protoc_insertion_point(class_scope:EntityJoinWorldEvent)

class PopulationUpdateEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POPULATIONUPDATEEVENT
  
  # @@protoc_insertion_point(class_scope:PopulationUpdateEvent)

class EntityGroupChangedEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYGROUPCHANGEDEVENT
  
  # @@protoc_insertion_point(class_scope:EntityGroupChangedEvent)

class EntityMoveEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYMOVEEVENT
  
  # @@protoc_insertion_point(class_scope:EntityMoveEvent)

class AttackEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACKEVENT
  
  # @@protoc_insertion_point(class_scope:AttackEvent)

class DamageEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DAMAGEEVENT
  
  # @@protoc_insertion_point(class_scope:DamageEvent)

class KillEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KILLEVENT
  
  # @@protoc_insertion_point(class_scope:KillEvent)


_EVENTSERVICE = descriptor.ServiceDescriptor(
  name='EventService',
  full_name='EventService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=672,
  serialized_end=1014,
  methods=[
  descriptor.MethodDescriptor(
    name='PlayerLogined',
    full_name='EventService.PlayerLogined',
    index=0,
    containing_service=None,
    input_type=_PLAYERLOGINEDEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='EntityJoinWorld',
    full_name='EventService.EntityJoinWorld',
    index=1,
    containing_service=None,
    input_type=_ENTITYJOINWORLDEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='PopulationUpdate',
    full_name='EventService.PopulationUpdate',
    index=2,
    containing_service=None,
    input_type=_POPULATIONUPDATEEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='EntityGroupChanged',
    full_name='EventService.EntityGroupChanged',
    index=3,
    containing_service=None,
    input_type=_ENTITYGROUPCHANGEDEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='EntityMove',
    full_name='EventService.EntityMove',
    index=4,
    containing_service=None,
    input_type=_ENTITYMOVEEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Attack',
    full_name='EventService.Attack',
    index=5,
    containing_service=None,
    input_type=_ATTACKEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Damage',
    full_name='EventService.Damage',
    index=6,
    containing_service=None,
    input_type=_DAMAGEEVENT,
    output_type=_VOID,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Kill',
    full_name='EventService.Kill',
    index=7,
    containing_service=None,
    input_type=_KILLEVENT,
    output_type=_VOID,
    options=None,
  ),
])

class EventService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _EVENTSERVICE
class EventService_Stub(EventService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _EVENTSERVICE

# @@protoc_insertion_point(module_scope)
